### ISSUE TITLE
请问出现这个问题是什么原因啊

### ISSUE THREAD

**Issue by ZRJ026** [hbkooo/HPVOrder#2]
![image](https://user-images.githubusercontent.com/52122544/120627234-0b615a00-c496-11eb-84b6-a6d61e2d82c4.png)
改了tk，没有改cookie，我获取到的cookie没有你的多，不知道咋改，要改cookie吗

邮件里是这样的
![image](https://user-images.githubusercontent.com/52122544/120630120-15d12300-c499-11eb-92fc-fdffc10ac025.png)

**Comment by hbkooo** [comment]
> ![image](https://user-images.githubusercontent.com/52122544/120627234-0b615a00-c496-11eb-84b6-a6d61e2d82c4.png)
> 改了tk，没有改cookie，我获取到的cookie没有你的多，不知道咋改，要改cookie吗
> 
> 邮件里是这样的
> ![image](https://user-images.githubusercontent.com/52122544/120630120-15d12300-c499-11eb-92fc-fdffc10ac025.png)

你 pip list 看一下你的 requests 包的版本，版本过高可能会导致这个错误。你降低一下版本，降低到2.22或2.21。

**Comment by ZRJ026** [comment]
> > ![image](https://user-images.githubusercontent.com/52122544/120627234-0b615a00-c496-11eb-84b6-a6d61e2d82c4.png)
> > 改了tk，没有改cookie，我获取到的cookie没有你的多，不知道咋改，要改cookie吗
> > 邮件里是这样的
> > ![image](https://user-images.githubusercontent.com/52122544/120630120-15d12300-c499-11eb-92fc-fdffc10ac025.png)
> 
> 你 pip list 看一下你的 requests 包的版本，版本过高可能会导致这个错误。你降低一下版本，降低到2.22或2.21。

改到2.21了，可以订阅，太感谢了
